Repository jakkulabs/PowervRA, pull requests merged in 2023-07, with the labels that each got.

#288 Fixes deprecated/removed auth API endpoint - Issue #287
  src/Functions/Public/Connect-vRAServer.ps1
Labels: bug, vRA 8.x+

#291 Removed test_release job
  .github/workflows/ps-module.yml
Labels: bug, CI Pipeline

#286 Allow username to be an email address
  src/Functions/Public/Connect-vRAServer.ps1
Labels: enhancement, vRA 8.x+

#292 Updated readme for v6.0.0
  README.md
Labels: bug, vRA 8.x+

#293 Add README.md to GitHub Actions trigger
  .github/workflows/ps-module.yml
Labels: enhancement, CI Pipeline
